### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by Cookie04DE** [Phyremaster/papermc-docker#12]
Please consider adding a license so there  are no legal uncertainties, and changing and running your code is actually legal.

**Comment by Phyremaster** [comment]
Legal documents are stupid and should be avoided if reasonably feasible. I'm the only one who could take legal action against someone for modifying and/or running this code, and I'm not going to do that because that would be stupid, pointless, and most importantly a dick move. If PaperMC, Mojang, or Microsoft could take legal action against me or anyone else for this, a license would do absolutely nothing to stop that, unless they require usage of a license in their license, but that probably wouldn't apply anyway since this project does not directly redistribute Minecraft or PaperMC. Also, I checked the repository for Paper, and the licenses folder contains the MIT license, which basically says that anyone can do whatever they want with the project so long as the license is always included with it; since this project downloads Paper from PaperMC, if this project manages to generate a copy of Paper that is missing the license, it's PaperMC's fault.
