### ISSUE TITLE
Restarting server

### ISSUE THREAD

**Issue by 82amp** [Phyremaster/papermc-docker#48]
Not sure if an issue with papermc-docker, but when running "restart" from the console (and I presume via rcon as well), it fails to actually restart the server. Once the java application exits, the container exits.

I have not got the `--restart always` parameter

Should I have the `--restart always` parameter, and if so, how do I then safely stop the server? Or, is there a different mechanism to restart from console/rcon without the entire docker image going down?

**Comment by Phyremaster** [comment]
[Here is the Docker documentation for restart policies.](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy) I'm not quite sure why running `restart` in the console doesn't restart the server before the container exits, but I'm pretty sure that it's because the `restart` command doesn't actually restart the Minecraft server (it only stops the server, I think).
If you want stopping the server from its console (or with an in-game OP command) to restart the container, you need the restart policy to be `always` or `unless-stopped`. If you _don't_ want it to restart when stopped via the console (but do want it to restart if it crashes), you need the restart policy to be `on-failure`.
To stop or restart the container (which should safely stop the server inside before the container stops), use the `docker container stop <container name>` or `docker container restart <container name>` commands, respectively. You will probably need to throw a `sudo` before those, unless your system is configured to avoid that, or you're on Windows. Basically, if you stop/restart the container through Docker, it should send the Java application the "stop" signal and wait for it to exit normally before stopping/restarting the container.
If for some reason the Java application is _not_ exiting properly before the container stops/restarts, please reopen this issue.
